import { describe, expect, it } from 'vitest';
import { getDefaultEditorPassword, hashPassword, verifyPassword } from '../../lib/auth/password';

describe('editor password hashing', () => {
  it('verifies a password generated by hashPassword', () => {
    const hash = hashPassword('sample-secret');
    expect(verifyPassword('sample-secret', hash)).toBe(true);
  });

  it('rejects invalid password input', () => {
    const hash = hashPassword('sample-secret');
    expect(verifyPassword('wrong-password', hash)).toBe(false);
  });

  it('uses env override for default editor password', () => {
    const previous = process.env.DEFAULT_PASSWORD;
    process.env.DEFAULT_PASSWORD = 'custom-secret';
    expect(getDefaultEditorPassword()).toBe('custom-secret');
    process.env.DEFAULT_PASSWORD = previous;
  });

  it('falls back to password when env is missing', () => {
    const previous = process.env.DEFAULT_PASSWORD;
    delete process.env.DEFAULT_PASSWORD;
    expect(getDefaultEditorPassword()).toBe('password');
    process.env.DEFAULT_PASSWORD = previous;
  });
});
